## Problem 28: Create a MATLAB command A(2, :) = ... for the new row 2, to subtract 3 times row 1 from the existing row 2 if the matrix A is already known. 

In [1]:
import numpy as np 

In [15]:
# create any matrix

A = np.array([[1, 2, 3], 
             [4, 5, 6], 
            [7, 8, 9]])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
A[1, :] = A[1, :] - 3*A[0, :] # since python indexing starts from 0

In [17]:
print(A)

[[ 1  2  3]
 [ 1 -1 -3]
 [ 7  8  9]]


## Problem 29: Find experimentally the average 1st, 2nd, and 3rd pivot sixes from MATLAB's [L, U] = lu(rand(3)). The average size abs(U(1, 1)) is above 1/2 because lu picks the largest available pivot in column 1. Here A = rand(3) has random enteries between 0 and 1. 

In [20]:
import scipy.linalg

In [25]:
first_pivots = []
second_pivots = []
third_pivots = []

for _ in range(1000):
    A = np.random.rand(3,3)
    P, L, U = scipy.linalg.lu(A)
    first_pivots.append(U[0,0])
    second_pivots.append(U[1,1])
    third_pivots.append(U[2,2])
print("Average value of first pivot  - ", sum(first_pivots) / len(first_pivots))
print("Average value of second pivot - ", sum(second_pivots) / len(second_pivots))
print("Average value of third pivot  - ", sum(third_pivots) / len(third_pivots))


Average value of first pivot  -  0.7529032934680416
Average value of second pivot -  0.35997730362058733
Average value of third pivot  -  0.19425264111272766


The pivots are in the decreasing order as mentioned in the question.