<a href="https://colab.research.google.com/github/hardikkamboj/Introduction_to_Linear_Algebra/blob/main/Chapter-2/Problem_set_2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Problem 36: The Hilbert matrices have Hij = 1 / (i + j - 1). Ask MATLAB for the exact 6 by 6 inverse invhilb(6). Then ask it to convert inverse (hilb(6)). How can these be different, when the computer nevere makes any mistake?

In [42]:
import scipy.linalg as linalg
import numpy as np

In [28]:
# let's first see what a hilbert matrix looks like

hilbert = linalg.hilbert(6)

print(hilbert)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909]]


In [29]:
# get inverse hilbert using the function invhilbert
inv_hilbert = linalg.invhilbert(6)

print(inv_hilbert)

[[ 3.60000e+01 -6.30000e+02  3.36000e+03 -7.56000e+03  7.56000e+03
  -2.77200e+03]
 [-6.30000e+02  1.47000e+04 -8.82000e+04  2.11680e+05 -2.20500e+05
   8.31600e+04]
 [ 3.36000e+03 -8.82000e+04  5.64480e+05 -1.41120e+06  1.51200e+06
  -5.82120e+05]
 [-7.56000e+03  2.11680e+05 -1.41120e+06  3.62880e+06 -3.96900e+06
   1.55232e+06]
 [ 7.56000e+03 -2.20500e+05  1.51200e+06 -3.96900e+06  4.41000e+06
  -1.74636e+06]
 [-2.77200e+03  8.31600e+04 -5.82120e+05  1.55232e+06 -1.74636e+06
   6.98544e+05]]


In [30]:
# calculate inverse using inverse function

inv_hilbert_2 = linalg.inv(hilbert)

print(inv_hilbert_2)

[[ 3.60000e+01 -6.30000e+02  3.36000e+03 -7.56000e+03  7.56000e+03
  -2.77200e+03]
 [-6.30000e+02  1.47000e+04 -8.82000e+04  2.11680e+05 -2.20500e+05
   8.31600e+04]
 [ 3.36000e+03 -8.82000e+04  5.64480e+05 -1.41120e+06  1.51200e+06
  -5.82120e+05]
 [-7.56000e+03  2.11680e+05 -1.41120e+06  3.62880e+06 -3.96900e+06
   1.55232e+06]
 [ 7.56000e+03 -2.20500e+05  1.51200e+06 -3.96900e+06  4.41000e+06
  -1.74636e+06]
 [-2.77200e+03  8.31600e+04 -5.82120e+05  1.55232e+06 -1.74636e+06
   6.98544e+05]]


In [31]:
# although they look similar, but there's a catch. let's look at the first and last element in both of the matrices
inv_hilbert == inv_hilbert_2

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [32]:
# Using the method linalg.invhilbert
print("First element - ", inv_hilbert[0][0])
print("Last  element - ", inv_hilbert[5][5])

First element -  36.0
Last  element -  698544.0


In [33]:
# using linalg.inv on hilbert
print("First element - ", inv_hilbert_2[0][0])
print("Last  element - ", inv_hilbert_2[5][5])

First element -  36.00000000190175
Last  element -  698544.0000880137


If we convert the datatytpe to int, then they are similar

In [34]:
inv_hilbert.astype("int") == inv_hilbert_2.astype("int")

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

# Problem 37:

a. Use inv(P) to invert MATLAB's 4 by 4 symmetric matrix P = Pascal(4)

b. Create Pascal's lower triangular abs(pascal(4,1)) and test P = LL'.

In [46]:
P = linalg.pascal(4)
P

array([[ 1,  1,  1,  1],
       [ 1,  2,  3,  4],
       [ 1,  3,  6, 10],
       [ 1,  4, 10, 20]], dtype=uint64)

In [39]:
linalg.inv(P)

array([[  4.,  -6.,   4.,  -1.],
       [ -6.,  14., -11.,   3.],
       [  4., -11.,  10.,  -3.],
       [ -1.,   3.,  -3.,   1.]])

In [41]:
L = linalg.pascal(4, kind = "lower")

L

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 2, 1, 0],
       [1, 3, 3, 1]], dtype=uint64)

In [44]:
# test P = L*L'

L@np.transpose(L)

array([[ 1,  1,  1,  1],
       [ 1,  2,  3,  4],
       [ 1,  3,  6, 10],
       [ 1,  4, 10, 20]], dtype=uint64)

In [48]:
(P == L@np.transpose(L)).all()

True

### Problem 38. If A = ones(4) and b = rand(4, 1), how does MATLAB tell you that Ax=b has no solution? For the special b = ones(4,1), which solution is found to Ax=b by A / b?

In [55]:
A = np.ones((4,4))
b = np.random.rand(4,1)

print(A)
print("")
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0.81447213]
 [0.74180632]
 [0.65111386]
 [0.50084777]]


In [59]:
# For Ax=B to have a soltion, X = A-1*B. So, inverse of A should exist. In this case A is a singular matrix

linalg.solve(A, b)

LinAlgError: Matrix is singular.

In [60]:
b = np.ones((4,1))

linalg.solve(A, b)

LinAlgError: Matrix is singular.