In [1]:
import numpy as np

### Problem 25 For the 6 by 6 second diggerence constan-diagonal matrix K, put the pivots and multipliers into K=LU. (L and U will have only two nonzero diagonals, because K has 3). Find a formula for the i,j entry of L-1, by software like MATLAB using inv(L) or by looking for a nice pattern

In [8]:
L = np.array([[ 2, -1,  0,  0,  0,  0], 
             [-1,  2, -1,  0,  0,  0], 
             [ 0, -1,  2, -1,  0,  0],
             [ 0,  0, -1,  2, -1,  0],
             [ 0,  0,  0, -1,  2, -1],
             [ 0,  0,  0,  0, -1, -2]])

In [9]:
print(L)

[[ 2 -1  0  0  0  0]
 [-1  2 -1  0  0  0]
 [ 0 -1  2 -1  0  0]
 [ 0  0 -1  2 -1  0]
 [ 0  0  0 -1  2 -1]
 [ 0  0  0  0 -1 -2]]


In [10]:
np.invert(L)

array([[-3,  0, -1, -1, -1, -1],
       [ 0, -3,  0, -1, -1, -1],
       [-1,  0, -3,  0, -1, -1],
       [-1, -1,  0, -3,  0, -1],
       [-1, -1, -1,  0, -3,  0],
       [-1, -1, -1, -1,  0,  1]])

## Pattern for L inv

In [7]:
L.shape

(5, 6)

In [11]:
def L_inv(L):
    h, w = L.shape
    A = np.zeros_like(L)
    
    for i in range(h):
        for j in range(w):
            if i == j:
                A[i][j] = -3 
            elif abs(i-j) == 1:
                A[i][j] = 0
            else:
                A[i][j] = -1
    return A

In [12]:
print(L_inv(L))

[[-3  0 -1 -1 -1 -1]
 [ 0 -3  0 -1 -1 -1]
 [-1  0 -3  0 -1 -1]
 [-1 -1  0 -3  0 -1]
 [-1 -1 -1  0 -3  0]
 [-1 -1 -1 -1  0 -3]]
