In [22]:
import numpy as np
import scipy.linalg as linalg

### Problem 25 For the 6 by 6 second diggerence constan-diagonal matrix K, put the pivots and multipliers into K=LU. (L and U will have only two nonzero diagonals, because K has 3). Find a formula for the i,j entry of L-1, by software like MATLAB using inv(L) or by looking for a nice pattern

In [26]:
K = linalg.toeplitz([2, -1, 0, 0, 0, 0])

print(K)

[[ 2 -1  0  0  0  0]
 [-1  2 -1  0  0  0]
 [ 0 -1  2 -1  0  0]
 [ 0  0 -1  2 -1  0]
 [ 0  0  0 -1  2 -1]
 [ 0  0  0  0 -1  2]]


In [28]:
K_inv = linalg.inv(K)

print(K_inv)

[[0.85714286 0.71428571 0.57142857 0.42857143 0.28571429 0.14285714]
 [0.71428571 1.42857143 1.14285714 0.85714286 0.57142857 0.28571429]
 [0.57142857 1.14285714 1.71428571 1.28571429 0.85714286 0.42857143]
 [0.42857143 0.85714286 1.28571429 1.71428571 1.14285714 0.57142857]
 [0.28571429 0.57142857 0.85714286 1.14285714 1.42857143 0.71428571]
 [0.14285714 0.28571429 0.42857143 0.57142857 0.71428571 0.85714286]]


### Problem 26: If you print K-1, it doesn't look so good. But if you print 7K-1, that matrix looks wonderful

In [31]:
7*K_inv

array([[ 6.,  5.,  4.,  3.,  2.,  1.],
       [ 5., 10.,  8.,  6.,  4.,  2.],
       [ 4.,  8., 12.,  9.,  6.,  3.],
       [ 3.,  6.,  9., 12.,  8.,  4.],
       [ 2.,  4.,  6.,  8., 10.,  5.],
       [ 1.,  2.,  3.,  4.,  5.,  6.]])

It indeed looks wonderful : D 